name: mi primer workflows

on:
  push:
    branches: [rama1]

jobs: 
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: ejecuta un saludo
        run: echo "hola mundo!"

      - name: lista de archivos
        run: ls -R
